### ISSUE TITLE
前后端分离，如何实现树形多级权限分组显示

### ISSUE THREAD

**Issue by wayne798** [windhoney/yii2-rest-rbac#23]
基于当前的实现，根据parent_name可以将路由分组，但是只是二级目录显示，一般我们给前端的是树形多级分组
|----客户
|    |----客户管理
|    |    |----添加客户
|    |    |----删除客户
|----订单
|    |----订单管理
    
其实真正的叶子节点才是权限，目前我采取的方案是，新增auth_group表，这个表存的树形的分组，
|id | name | parent|
将auth_item表中的parent_name改成goup_id,即关联auth_group表中的id。
想让某个权限节点在哪一层分组就赋予对应的group_id，这样的话，我们只关心两点，一是权限分组结构，二是某个权限放在哪个分组。这样分开处理后，更加清晰和容易管理，而且可以实现树形多级分组。

**Comment by windhoney** [comment]
你这种方法就可以，我之前写的比较简单

**Comment by wayne798** [comment]
@windhoney 可以加个QQ吗，496577309 借一步说话😆😁
