### ISSUE TITLE
composer.json没有PHP版本的信息

### ISSUE THREAD

**Issue by ansonhorse** [windhoney/yii2-rest-rbac#27]
`??`应该是PHP7新增的吧。
我测试环境是PHP5.6，可以通过composer安装这个模块，但因为有类似开头说的PHP7的特性，所以运行时就报错了：
```
syntax error, unexpected '?'
```
所以，希望可以增加requirements之类的说明，或者在composer.json里做限制。

**Comment by windhoney** [comment]
好的 我处理一下

**Comment by windhoney** [comment]
> `??`应该是PHP7新增的吧。
> 我测试环境是PHP5.6，可以通过composer安装这个模块，但因为有类似开头说的PHP7的特性，所以运行时就报错了：
> 
> ```
> syntax error, unexpected '?'
> ```
> 所以，希望可以增加requirements之类的说明，或者在composer.json里做限制。

好的 我处理一下
