### ISSUE TITLE
models/Menu里的表名hard code问题

### ISSUE THREAD

**Issue by ansonhorse** [windhoney/yii2-rest-rbac#28]
https://github.com/windhoney/yii2-rest-rbac/blob/4cbd9ee902495b1787075ad9688d57bd86bd1a00/models/Menu.php#L199

这个是不是可以通过`authManager`来获取？
```php
Yii::$app->getAuthManager()->itemTable
```

**Comment by ansonhorse** [comment]
顺便说一个疑问：
`components/DbManager.php`里的`groupTable`和`groupChildTable`都是静态属性，我的疑问是，为什么不跟`itemTable`这些一样，定义为常规的属性，这样就可以在配置`authManager`时指定这两个表名了。

**Comment by windhoney** [comment]
> 顺便说一个疑问：
> `components/DbManager.php`里的`groupTable`和`groupChildTable`都是静态属性，我的疑问是，为什么不跟`itemTable`这些一样，定义为常规的属性，这样就可以在配置`authManager`时指定这两个表名了。

项目中还是有一些不完善的地方待优化！

**Comment by ansonhorse** [comment]
哈哈当然，所谓众人拾柴火焰高，会越来越好用的。

**Comment by windhoney** [comment]
> 哈哈当然，所谓众人拾柴火焰高，会越来越好用的。

有时间在重新整理整理，完善一下，感谢提出问题。哈哈~~
