### ISSUE TITLE
wind\rest\components\Configs

### ISSUE THREAD

**Issue by Mercis** [windhoney/yii2-rest-rbac#33]
class Configs extends \yii\base\Object  调整为 extends \yii\base\BaseObject
调整public $menuTable = '{{%menu}}';public $userTable = '{{%user}}';

**Comment by windhoney** [comment]
BaseObject已经调整，表名问题暂未修改

**Comment by Mercis** [comment]
大部分项目还是有表前缀的，之前我都是手动改你的源码，觉得不合适，你这边调整一下吧

**Comment by windhoney** [comment]
之前是有的，我这边先测试一下 有些sql可能有点影响

**Comment by Mercis** [comment]
OK,yii2-admin包里面也是用的{{%menu}}

**Comment by windhoney** [comment]
好了

**Comment by Mercis** [comment]
composer 包也替换一下，谢谢

**Comment by windhoney** [comment]
> composer 包也替换一下，谢谢

更新..
